### ISSUE TITLE
FPS

### ISSUE THREAD

**Issue by clongcw** [Weltolk/R3nzSkin_tool#5]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Weltolk** [comment]
> 使用成功了，但是FPS疯狂掉

本项目只是单纯的通过替换文件来达到在国服注入r3nzskin的功能,这应该是r3nzskin本身的问题

现在我测试了一下,通过将文件替换game目录下的为hid.dll文件,可以正常注入并且不掉fps

暂时先关闭,有问题麻烦再开启

**Comment by Weltolk** [comment]
> 使用成功了，但是FPS疯狂掉

已更新新版,新版通过替换hid.dll来注入,测试可用,且不掉fps

https://github.com/Weltolk/R3nzSkin_tool/releases
