### ISSUE TITLE
对国服有用吗？我试了下国服，不起作用

### ISSUE THREAD

**Issue by Zcaic** [Weltolk/R3nzSkin_tool#6]

**Comment by Weltolk** [comment]
本项目主要就是针对国服,通过替换文件来达到注入的

这应该是r3nzskin本身的问题

刚刚我测试了将文件替换为hid.dll,可以正常使用

暂时先关闭了,有问题麻烦再开启

**Comment by Weltolk** [comment]
> _No description provided._

已更新新版,新版通过替换hid.dll来注入,测试可用,且不掉fps

https://github.com/Weltolk/R3nzSkin_tool/releases

**Comment by Zcaic** [comment]
十分感谢！！！
